# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 05:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='username')),
                ('email', models.EmailField(max_length=30, unique=True, verbose_name='email')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='name')),
                ('role', models.CharField(choices=[('Admin', 'Administrator'), ('User', 'CommonUser')], default='User', max_length=10, verbose_name='role')),
                ('wechat', models.CharField(blank=True, max_length=30, verbose_name='wechat')),
                ('CellPhoneNumber', models.CharField(blank=True, max_length=30, verbose_name='CellPhoneNumber')),
                ('CreateTime', models.DateTimeField(auto_now_add=True, verbose_name='CreateTime')),
                ('UpdateTime', models.DateTimeField(blank=True, verbose_name='UpdateTime')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GroupName', models.CharField(max_length=50, unique=True, verbose_name='GroupName')),
                ('CreateTime', models.DateTimeField(auto_now_add=True, verbose_name='CreateTime')),
                ('UpdateTime', models.DateTimeField(verbose_name='UpdateTime')),
                ('GroupType', models.CharField(max_length=30, unique=True, verbose_name='GroupType')),
            ],
        ),
        migrations.CreateModel(
            name='SystemUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=50, unique=True, verbose_name='UserName')),
                ('Password', models.CharField(max_length=100, verbose_name='Password')),
                ('CreateTime', models.DateTimeField(auto_now_add=True, verbose_name='CreateTime')),
                ('UpdateTime', models.DateTimeField(verbose_name='UpdateTime')),
                ('key', models.CharField(max_length=100, verbose_name='key')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='Group_ID',
            field=models.ManyToManyField(to='user.Group'),
        ),
        migrations.AddField(
            model_name='user',
            name='SystemUser_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.SystemUser'),
        ),
    ]
