# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20171103_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='UpdateTime',
            field=models.DateTimeField(null=True, verbose_name='UpdateTime'),
        ),
        migrations.AlterField(
            model_name='systemuser',
            name='UpdateTime',
            field=models.DateTimeField(null=True, verbose_name='UpdateTime'),
        ),
        migrations.AlterField(
            model_name='user',
            name='UpdateTime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='UpdateTime'),
        ),
    ]
