# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 07:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20171103_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='SystemUser_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.SystemUser'),
        ),
    ]
