# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20171108_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_img',
            field=models.CharField(default='dist/img/default.jpeg', max_length=100),
        ),
    ]
