# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_user_uer_absolute_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='update_description',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
