# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_user_update_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Group_ID',
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, choices=[('ops', 'OperationEngineer'), ('dev', 'Development Engineer;')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='log_path',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
