# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 11:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20171116_1056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='update_description',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='user',
            name='UpdateTime',
        ),
    ]
