# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 03:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20171116_1112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='role',
            new_name='user_role',
        ),
    ]
