# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 03:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20171117_0345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('Admin', 'Administrator'), ('User', 'CommonUser')], max_length=10, verbose_name='role'),
        ),
    ]
