# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20171120_0402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(choices=[('ops', 'Operation Engineer'), ('dev', 'Development Engineer')], max_length=30, null=True),
        ),
    ]
