# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-21 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_auto_20171121_0629'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemuser',
            name='admin_active',
            field=models.BooleanField(default=False),
        ),
    ]
