# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_systemuser_admin_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='SystemUser_ID',
        ),
        migrations.AddField(
            model_name='user',
            name='SystemUser_ID',
            field=models.ManyToManyField(null=True, to='user.SystemUser'),
        ),
    ]
