# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 08:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_auto_20171122_0211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemuser',
            name='user_role',
        ),
    ]
