# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 02:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_remove_systemuser_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemuser',
            name='admin_active',
        ),
        migrations.RemoveField(
            model_name='systemuser',
            name='key',
        ),
        migrations.AddField(
            model_name='systemuser',
            name='private_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemuser',
            name='public_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='systemuser',
            name='Password',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Password'),
        ),
    ]
