# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-21 07:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_auto_20171221_0652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_permission',
        ),
        migrations.AddField(
            model_name='permission',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
