# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-21 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_auto_20171221_0748'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='random_code',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
