# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-22 07:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_user_random_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='random_code',
        ),
    ]
