BBBBBBB BBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBB
BBBBB BBBBBBBBBB
    XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
BBBBBBBB
BBBBB BBBBBBB
XXXX
XXXXX
     XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX

                  BBBBBBBBBB
                  BB BBBBBBBBBBB
                      BBB BB BBBBBBB BB BBBBBBBBBBBBBBBBB
                        XX XXXXXXXXXXXXXXXXXXXXXX
                      BBBBBB
                  BBBBB
        XXXX XXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXX
            XXXXXX
        XXXXXX

        XXXX XXXXXXXXXXXXXXXXXXX
             XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXX
                    BBB BBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                        XXXXXXX XXXXXXXXXXXXXXXXXX
                    BBBBBB
                XXXXXXXXX
            XXXXXX
        XXXXXX


        XXXX XXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
             XXXX XXXXXXXXXXXXXXXXX
                XXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
             XXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX
            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX
        XXXXXX
     XXXXXXX
XXXXXX

BBBBBBBB

BBBBB BBBBBBB
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX

            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXX X  XXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXX
BBBBBBBB