BBBBBBB BBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBB
BBBBB BBBBBBB
XXXX
XXXXX
     XXXX XXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXX
              XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX

              XXXX XXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXX
                  XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX

                  XXXX XXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                  XXXXXX
                XXXXXX
              XXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXX XXX
            XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX
              XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX
                XXXX
                  XXXXXXXXXXXX
                  XXXXXXXXXXXXXX
                  XXXXXXXXXXXXX
                  XXXXXXXXXXXXX
                  XXXXXXXXXXX
                XXXXX
               BBB BBBBBBBBBBB BB BBBBBBBBBBBBBBBB
                    XXXX
                      XXXXXXXXX
                      XXXXXXXXX
                      XXXXXXXXX
                      XXXXXXXXX
                      XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXX
                BBBBBB
              XXXXXXXX
            XXXXXX
            XXXX XXXXXXXXXX XXX
          XXXXXX
          XXXX XXXXX XXX
        XXXXXX
    XXXXXX
BBBBBBBB

BBBBB BBBBBBB
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
     XXXXXXXXXXXXX
     XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX X
         XXXXXXXX XXXXXXXXXXXXXXX X
             XXX XXXXXXXXXXX X XXXXX
             XX XXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXX XX XXX X
                 XXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXX
                 XXX XXXX X X XX X X XXXXXXXXXXXXXXX XXXX X
                     XXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXX
                     XX XXXX XXXX XXXXXX XXXXXX XXXXX XXXX XXX XXXX XX XXXXX
                     XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX X XX XX XXXXX X XXXXX X
                         XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXX
                         XXXXXX
                     X
                 X
             X
             XXXXXX XXXXXXXXXXXX
         X
         XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
             XX XXXX XXXX XXX XXXXX XX XXXXXXXX XXXX XXXX XXXXXXXX
             XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
         X
     X
XXX
     XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
          XXXXXXXX
               XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXX
               XXXXXXXXXXXXXX
               XXXXXXX X XXXXXXXX XXXXXXXX X
                   XXXXXXXXXXXXXXXXXXXX

               X
            XXX
     X
     XXXXXXXXX
BBBBBBBB