BBBBBBB BBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBB
BBBBB BBBBBBB
XXXX
  XXXXX
    XXXX XXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXX
              XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX

              XXXX XXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXX
                  XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX

                  XXXX XXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                  XXXXXX
                XXXXXX
              XXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXX XXX
            XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX
              XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX
                XXXX
                  XXXXXXXXXXXX
                  XXXXXXXXXXXXX
                  XXXXXXXXXXXXXX
                  XXXXXXXXXXXXX
                  XXXXXXXXXXXXXX
                  XXXXXXXXXXXXX
                  XXXXXXXXXXX
                  XXXXXXXXXXX
                XXXXX
                BBB BBBBBBBB BB BBBBBBBBB
                  XXXX
                    XXXXXXXXX
                    XXXXXXXXX
                    XXXXXXXXX
                    XXXXXXXXX
                    XXXXXXXXX
                    XXXXXXXXX
                    XXXXXXXXX
                    XXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                  XXXXX
                BBBBBB
              XXXXXXXX
            XXXXXX
            XXXX XXXXXXXXXX XXX
          XXXXXX
          XXXX XXXXX XXX
        XXXXXX
  XXXXXX
BBBBBBBB

