BBBBBBB BBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBB
BBBBB BBBBBBB
XXXXX
 XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX

              BBBBBBBBBB
              BB BBBBBBBBBBB
                  BBB BB BBBBBBB BB BBBBBBBBBBBBBBBBB
                    XX XXXXXXXXXXXXXXXXXXXXXX
                  BBBBBB
              BBBBB
      XXXX XXXXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXX
        XXXXXX
    XXXXXX

     XXXX XXXXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX
             XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXX
                    BBB BBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                           XXXXXXX XXXXXXXXXXXXXXXXXX
                    BBBBBB
             XXXXXXXXX
        XXXXXX
    XXXXXX

     XXXX XXXXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX
             XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXX
                    BBB BBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                           XXXXXXX XXXXXXXXXXXXXXXXXX
                    BBBBBB
             XXXXXXXXX
        XXXXXX
    XXXXXX

     XXXX XXXXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX
             XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXX
                 BBB BBBBBBBB BB BBBBBBBBB
                    
                 BBBBBB
             XXXXXXXXX
        XXXXXX
    XXXXXX

    XXXX XXXXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
         XXXX XXXXXXXXXXXXXXXXX
            XXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
         XXXXXX
    XXXXXX

     XXXX XXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX
    XXXXXX
 XXXXXXX
    XXXXXX
BBBBBBBB