BBBBBBB BBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBB
BBBBB BBBBBBB
  XXXXX
     XXXX XXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXX
              XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

              XXXX XXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXX
                  XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX

                  XXXX XXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                  XXXXXX
                XXXXXX
              XXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXX XXX
            XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX
              XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX
                XXXX
                  XXXXXXXXXXXX
                  XXXXXXXXXXXX
                  XXXXXXXXXXXXXXXXX
                  XXXXXXXXXXX
                XXXXX
                BBB BBBBBBBBBBBBBB BB BBBBBBBBBBBBBBB
                  XXXX
                    XXXXXXXXX
                    XXXXXXXXX
                    XXXXXXXXX
                    XXXXXX XXXXXXXXXXXXXXXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                  XXXXX
                BBBBBB
              XXXXXXXX
            XXXXXX
            XXXX XXXXXXXXXX XXX
          XXXXXX
          XXXX XXXXX XXX
        XXXXXX
    XXXXXX
BBBBBBBB

BBBBB BBBBBBB
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX X
        X
      X

    XXXXXXXXX
BBBBBBBB