# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-12 10:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asset', '0010_auto_20171204_1048'),
        ('user', '0023_auto_20171129_0234'),
    ]

    operations = [
        migrations.CreateModel(
            name='perm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('CreateTime', models.DateTimeField(auto_now_add=True)),
                ('perm', models.CharField(choices=[('Admin', '管理权限'), ('Comman', '普通权限')], default='Comman', max_length=30)),
                ('descriptions', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=False)),
                ('SystemUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.SystemUser')),
                ('asset_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.AssetGroup')),
            ],
        ),
    ]
