# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-13 08:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perm',
            name='SystemUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.SystemUser'),
        ),
        migrations.AlterField(
            model_name='perm',
            name='asset_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='asset.AssetGroup'),
        ),
    ]
