# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-30 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='asset_env',
            field=models.CharField(choices=[('prod', '生产环境'), ('dev', '开发环境'), ('test', '测试环境')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_status',
            field=models.CharField(choices=[('In use', '使用中'), ('Out of use', '没在使用')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('server', '服务器'), ('networkdevice', '网络设备'), ('vm', '虚拟机'), ('firewall', '防火墙')], default='server', max_length=64, null=True),
        ),
    ]
