# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-01 03:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0003_auto_20171130_0656'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('descriptions', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_group',
            field=models.ManyToManyField(to='asset.AssetGroup'),
        ),
    ]
