# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-01 03:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0004_auto_20171201_0335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_group',
            field=models.ManyToManyField(default=None, to='asset.AssetGroup'),
        ),
    ]
