# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-02 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0005_auto_20171201_0359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='raid_type',
        ),
        migrations.AddField(
            model_name='server',
            name='sn',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='SN号'),
        ),
    ]
