# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-02 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0006_auto_20171202_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpu',
            name='cpu_core_count',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='cpu核数'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='cpu_count',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='物理cpu个数'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='capacity',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='ram',
            name='model',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='ram',
            name='slot',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
