# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-04 10:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0008_auto_20171204_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disk',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.Asset'),
        ),
        migrations.AlterField(
            model_name='nic',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.Asset'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.Asset'),
        ),
    ]
