# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-04 10:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0009_auto_20171204_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpu',
            name='asset',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='asset.Asset'),
        ),
    ]
