# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-21 04:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0010_auto_20171204_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='external_ip',
            field=models.GenericIPAddressField(blank=True, null=True, unique=True),
        ),
    ]
