# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-11 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0011_auto_20171221_0407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_status',
            field=models.CharField(choices=[('Online', '在线'), ('Not Online', '不在线')], default='In use', max_length=30, null=True),
        ),
    ]
