# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-09 07:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asset', '0011_auto_20171221_0407'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EndTime', models.DateTimeField(auto_created=True, auto_now=True)),
                ('User', models.CharField(max_length=30)),
                ('SystemUser', models.CharField(max_length=30)),
                ('SystemUserPerm', models.CharField(choices=[('Admin', '管理权限'), ('Comman', '普通权限')], default='Comman', max_length=30)),
                ('AssetGroup', models.CharField(max_length=30)),
                ('LogId', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('StartTime', models.DateTimeField(auto_now_add=True)),
                ('Asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.Asset')),
            ],
        ),
    ]
