# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-12 07:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='Asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Asset', to='asset.Asset'),
        ),
    ]
