BBBB BBBBBB

XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
XXXXXX
    XXXXX XXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX
    XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX
    XXXXXXX
        XXXXXXXXXXXXXXX X
          XXXXXXX XXXXXX
          XXXXXX XXXXX
          XXXXXXXXXXX XXXXX
          XXXXXXXXXXX XXXXX X X XXX XXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXX XXXXXXXX
          XXXXXXXXX XXXXXXX
        X

        XXXXXXXXXXXXXXX XXX X XXXXXXXX XXXXXX XXXXXXX XXXXX XXXXXXXXXX XXXXXX

        XXXXXXXX
        XXXXXXXXXXXXXXX X
          XXXXXXXXXXX XXXXX
          XXXXXXXXXXXXX XXXXX
          XXXXXXX XXX XXXXX XXXXX
          XXXXXXXXXXXXXX XXXX
          XXXXXXXXXXXXXXXXX XXXXX
          XXXXXXXXX XXXXXXX
          XXXXXXX XXXXX
          XXXXXX XXXXX
        X

        XXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXX XXXXX XXXXXXXXXXX X X XXX XXXXXXXXXXXXXXXXX

                XXXXXXXX
        XXXXXXXXXXXXXXXXXX XXXX
            XXXXXX XXXXX
            XXXXXXX X X XXX XXXX
            XXXXXXX XXX XXXX XXXXXX
            XXXXXXXXXXXXXX XXXX
            XXXXXXX XXXXXXXX
        X
        XXXXXXXXXXXXXXXXXX XXXXXXXXXX
            XXXXXXXXXXXXX XXXXX
            XXXXXXXXXXX X X XXX XXXXXXXXXXXXXXXX
        X

        XXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXXX XXXX XXXXXX XXXXXX
        X
        XXXXXX XXXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXXX XXXX XXXXXX XXXXXX
        X
    XXXXXXXX

XXXXXXX
XXXXXX
XXXX XXXXXXXXXXXXXXXXXX
    XXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXX
    XXXXXX
XXXXXX

XXXX XXXXXXXXXXXXXXXXX
    XXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXX XXXXXXX XXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBXXXXXXXX
        XX XXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXXXX
XXXXXX

XXXX XXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXXXX
    XXXXX
        XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
    XXXXXX

XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXX XXXXXXXXXXXXXXXXXXXX  XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX X
XXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX
XXXXXX


XXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXX
            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXXXXXX X XX XXXXXXXXXXXX
        XXXXXX

        XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
           BBB BBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBB
                XXXXX

                            BBB BBB BB BBBBBBBB
                                XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBX XX
                            BBBBBB

                XXXXXX
           BBBBBB

            XXXXXX
        XXXXXX
    XXXXXX
  XXXXXX
XXXXXX




XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXX
        XXXXXXXX
        XXX XXXXX X XXXXXXXXXXXXXXXXXX XXXXXX
        XXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXX XXXXX XXXXXXXX
            XXXXXXXXX XXXXXXX   XXXXXXX
            XXXXXXXXXXXXXX      XXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXX XXXXXX XXXXXXXXXXXXX
            XXXXXXXXXXXX XXXXXX XXXXXXXXXXX
            XXXXXXXXXXXX X X XX XXXXXX
            XXXXXXXXXXXXX XXXX  XXXXXXXXX
            XXXXXXXXXXXXX XX    XXXXXXXXX

            XXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXX XXX X
                XXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XX
        XXX


    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXX X XXXXXXXXXXX
        XX XXXXXX XX XXXXXXXXXXXXXX
            XXX XXXX X XXXXXXXXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
              XXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
              XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            X XXXX X
              XXXXXXXXXXXXXXXXXXXXX
            X
        X

XXX

    XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XXXXXXXX
    XXX XXXX X XXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXX XXXXXX

    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX


    XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

XXX

    XXX

     XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXX

     XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

        XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXX XXXXXXXXXXXXXX
            XXXXXX XXXXXX
        X

        XXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXX X XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXX
            XXXXX XXXXXXXXX
            XXXXXX XXXXXX
            XXXXXX XXXXXX
            XXXXXXXXXXXX XXXXXX
            XXXXXXXXXXXX XXXXXX
            XXXXXXXX XXXXXXXX XXXXXXX

                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXX
                    XXXXXXXXXXXXXXXX
                XXXXXX
                    XXXXXXXXXXXXXXXX
                X


            XX
            XXXXXX XXXXXXXX XXXXX X
                XXXXXXXXXXXXXXXXX X XXXXX
            X
        XXX
        XXXXXX XXXXXX
    XXX



XXXXXXXXX

XXXXXXX
XXXXXXX