BBBB BBBBBB
BBBB BBBB
XXXXXXXXX XXXXX
XXXXXX
XXXXXX
  XXXXX XXXXXXXXXXXXXXXX
  XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXXX X X XXX XXXXXXXXXX
  XXXX XXXX XXX XXXXXXX XX XX XXXXXXXXXX XX XXXXXX XXXXX XXX
  XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
  XXXX XXXXXXXXX XXXXX XXX
  XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX
  XXXX XXXX XXXXXXX XXX
  XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX
  XXXX XXXXXXXX XXX
  XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX
  XXXX XXXXX XXXXX XXX
  XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBXX
  XXXX XXXXXX XXX
  XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX

  XXXX XXXXX XXXX XXX XXXXXXXXXX XXX XXXXXXX XX XXXXX XXXXXXXX XXX XXXXX XXXXXXX XXX
  XXXX XXXXXXXX XXXXXXXXXX XXXXXXX XXXX XX XXX XXXX XXX XXXX XXX XXXXXXX XXX
  XXXXXXX XX XX XXX
  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXX

  XXXX XXXXXX XXXX XXX
  XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX
XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
XXXX XXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXX
    XX XXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXX
  XXXX XXXXXXXXXXXX XXX
  XXXX XXXXXXXXXXXXXXXXXXXXXXX
    XX XXXXXXXXXXXXXXXXXXXXXXXXXX XX XX XXXXX XXXX XXXXXXXXXXX

    XXXXX XXXXXXXXX XXXXXXXXXXXXXX
      BBBBBBBBBB
      BB BBBBBBBBBBB
          BBB BB BBBBBBB BB BBBBBBBBBBBBBBBBB
            XX XXXXXXXXXXXXXXXXXXXXXX
          BBBBBB
      BBBBB
      XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
        XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
        XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXX
      XXXX XXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXX XXXXXXXX
            XXXXXXX
              XXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XX
            XXXXXXXX
          XXXXXX
        XXXXXX
        XXXX XXXXX XXX
        XXXX XXXXXXXXXXXXXXXXX
          XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX
        XXXXXX
        XXXX XXXXX XXX
      XXXXXX
    XXXXXXX

    XXXX XXXXXXXXXXXXXXXXXXX XXX

    XX XXXXXXXXXX XXXXXX XX XXXXXXXXXXXXXXXX
    XX XXXXXXBBB BBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXX XXXXXXXXXXXXXX

  XXXXXX
  XXXX XXXXXXXXXXXXXXXX XXX
XXXXXX
XXXX XXXXXXXXXXX XXX

XXXX XXXXXX X XXX
XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
XXXX XXXXXXXXX XXXXX XXX
XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
XXXX XXXXXX XXX
XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
XXXXXXXX
  XXXXXXXXXX XX X
    XXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXX XXXXX XX XXXXXXXX XX
    XXX
  XXX
XXXXXXXXX
XXXXXXX
XXXXXXX
