BBBBBBB BBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBB
BBBBB BBBBBBB
  XXXX
      XXXXX
          XXXX XXXXXXXXXX XXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXX
              XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX
              BBBBBBBBBB
              BB BBBBBBBBBBB
                  BBB BB BBBBBBB BB BBBBBBBBBBBBBBBBB
                    XX XXXXXXXXXXXXXXXXXXXXXX
                  BBBBBB
              BBBBB

            XXXX XXXXXXXXXXXXXXXXX


              XXXX XXXXX XXXX XXX
              XXXX XXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXX

                XXXX XXXXXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXX XXXXXXXXXXXXXXXX
                  XXXXXX
                  XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX  XXXXXXXX
                XXXXXX
                XXXX XXXXXXX XXXXX XXX
              XXXXXX
              XXXX XXXXXX XXXXX XXX

              XXXX XXXXX XXXX XXX
              XXXX XXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXX

                XXXX XXXXXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXX XXXXXXXXXXXXX
                  XXXXXX
                  XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXX
                XXXXXX
                XXXX XXXXXXX XXXXX XXX
              XXXXXX
              XXXX XXXXXX XXXXX XXX

              XXXX XX XXXX XXX
                XXXX XXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXX


                  XXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXX XXXXXXXXXXX  XXXXXXXX XXXXXXXXXXXX
                    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                  XXXXXXXXX

                XXXX XXXXXXX XXXXX XXX
              XXXXXX

              XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX
              XXXX XXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXX

                XXXX XXXXXXXXXXXXXXXXXXXX

                  XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX
                XXXX XXXXXXX XXXXX XXX
              XXXXXX
              XXXXXX

              XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX
              XXXX XXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXX

                XXXX XXXXXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXX XXXXXXXXXXXX
                  XXXXXX
                  XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXX
                XXXXXX
                XXXX XXXXXXX XXXXX XXX
              XXXXXX

              XXXX XXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXX

                XXXX XXXXXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXX XXXXXXXXXXXX
                  XXXXXX
                  XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXX
                XXXXXX
                XXXX XXXXXXX XXXXX XXX
              XXXXXX
              XXXXXX
              XXXX XXXXXX XXXXX XXX
              XXXX XXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXX

                XXXX XXXXXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                  XXXXXX
                  XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXX
                XXXXXX
                XXXX XXXXXXX XXXXX XXX
              XXXXXX

               XXXXX
                  XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXX
            XXXXXX
              XXXXXXX
            XXXX XXXXXXXXXX XXX
          XXXXXX
        XXXXXX
BBBBBBBB
BBBBB BBBBBBB
  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
   XXXXXXXXXXXX X
       XXXXXXXXXXXXXXXXXXXXXXXXXXXXX


    XXX

  XXXXXXXX XXXXXXXXXXXXXXXX
      XXX XXXXX XX XXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXX
      X


  X
XXXXXXXXX
BBBBBBBB