BBBBBBB BBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBB
BBBB BBBB
BBBBB BBBBBBB
XXXX
 XXXXX XXXXXXXXX XXXXXXXXXXXXXX
      BBBBBBBBBB
      BB BBBBBBBBBBB
          BBB BB BBBBBBB BB BBBBBBBBBBBBBBBBB
            XX XXXXXXXXXXXXXXXXXXXXXX
          BBBBBB
      BBBBB
      

     XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXX

 XXXXXXX
BBBBBBBB