BBBBBBB BBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBB
BBBB BBBBBBBBBBB
BBBBB BBBBBBB
XXXX
XXXX XXXXXXXXXXXX
  XXXX XXXXXXXXXX XXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBXXXBBBBBBBBBBB BX XXXXXXXXX XXXXXXX XXXXXXXXX

                XXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX

                XX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX

                XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                  XXX XXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXX
                  XXXXX
                  XXX XXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXX
                  XXXXX
                    XXX XXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXX
                  XXXXX
                    XXX XXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXX
                  XXXXX
                  XXX XXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXX
                  XXXXX
                  XXX XXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXX
                  XXXXX
                  XXX XXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXX
                  XXXXX
                   XXX XXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXX
                  XXXXX
                XXXXX
              XXXXXX
              XXXX XXXXXXXXXX XXX
   XXXXXX
XXXXXX
BBBBBBBB